apps/posts/urls.py
from django.urls import path
from apps.posts.views import update_post,post_delete,comment_delete,search,home,completed,delete,filter_priority,filter_status

urlpatterns = [
    path('update_post/<int:id>/' , update_post,name='update_post'),
    path('post_delete/<int:id>/',post_delete,name='post_delete'),
    path('comment_delete/<int:id>/',comment_delete,name = 'comment_delete'),
    path('search/' , search ,name='search'),
    path('home/',home,name='home'),
    path('completed/<int:id>/',completed,name='completed'),
    path('delete/<int:id>/',delete,name='delete'),
    path('filter/choice/',filter_priority,name='priority'),
    path('status/choice/',filter_status,name='status'),
]

twitter/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.settings.urls')),
    path('users/', include('apps.users.urls')),
    path('posts/', include('apps.posts.urls'))
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/posts/models.py
from django.db import models
from apps.users.models import User

# Create your models here.

class Post(models.Model):
    text=models.TextField(
        max_length=500,
        blank=True,
        null=True
    )
    video=models.FileField(
        upload_to='post_video/',
        blank=True,
        null=True
    )
    image=models.ImageField(
        upload_to='post_image/',
        blank=True,
        null=True
    )
    user=models.ForeignKey(
        User,
        related_name='user_post',
        on_delete=models.CASCADE
    )
    
    created = models.DateTimeField(
        auto_now_add=True
    )
    
    def __str__(self):
        return self.user.username
    
    
    class Meta:
        verbose_name='post',
        verbose_name_plural='posts'

class Videos(models.Model):
    title=models.CharField(
        max_length=50
    )
    description=models.TextField(
        max_length=200
    )
    time_of =models.DateField(
        auto_now_add=True
    )
    video_file=models.FileField(
        upload_to='post_video/',
    )
    poster = models.ImageField(
        upload_to='post_poster/',
    )
    user = models.ForeignKey(
        User,
        related_name='user_video',
        on_delete=models.CASCADE
    )
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name='Видео'
        verbose_name_plural='Видео'
    
    
class Like(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='like_post',
        on_delete=models.CASCADE

    )
    user=models.ForeignKey(
        User,
        related_name='like_post',
        on_delete=models.CASCADE
    )
class Comment(models.Model):
    post=models.ForeignKey(
        Post,
        related_name='comment_post',  
        on_delete=models.CASCADE           
    )
    user= models.ForeignKey(
    User,
    related_name='comment_user',  
    on_delete=models.CASCADE                
    )
    text= models.CharField(
        max_length=255
    )
    created = models.DateTimeField(
        auto_now_add=True
    )
    
class LikeComment(models.Model):
    comment = models.ForeignKey(
        Comment, 
        related_name='like_comment',
        on_delete=models.CASCADE,
        
        )
    
    user = models.ForeignKey(
        User, 
        related_name='like_comment',
        on_delete=models.CASCADE,
        )

class Chat(models.Model):
    from_user=models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='from_user',
        verbose_name='Чат пользователя'
        )
    to_user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='to_user',
        verbose_name='Чат к пользователя',
        )

    class Meta:
        verbose_name="Чат"
        verbose_name_plural="Чаты"

class Message(models.Model):
    chat=models.ForeignKey(
        Chat,
        on_delete=models.CASCADE,
        related_name='message_chat',
        verbose_name='ID чата'
    )
    from_user=models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='chat_from_user',
        verbose_name="Сообщение от пользователя",
        )
    message=models.CharField(
        max_length=200,
        verbose_name='Сообщение'
    )
    created_at=models.TimeField(
        auto_now_add=True
    )
    def __str__(self):
        return f"{self.chat}"
    
    class Meta:
        verbose_name= "Сообщение в чате",
        verbose_name_plural= "Сообщение в чатах"


class Task(models.Model):
    Priority = (('L', 'Low'),
                ('M', 'Medium'),
                ('H', 'High'))
    task_name = models.CharField(
        max_length=50
    )
    du_date = models.DateTimeField(
        default=None, null=True ,blank = True
    )
    
    complated = models.BooleanField(
        default=False
    )
    priority = models.CharField(max_length =1,choices=Priority , default = 'L')
    
    def __str__(self):
        return self.task_title
    

apps/posts/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

class UpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

apps/posts/views.py
from django.shortcuts import render, redirect
from apps.posts.models import Post, Comment, Task
from apps.users.models import User
from apps.posts.forms import UpdateForm,TaskForm
from apps.settings.models import Settings
from django.db.models import Q
from .forms import TaskForm


# Create your views here.

def update_post(request, id):
    settings = Settings.objects.latest('id')
    post = Post.objects.get(id=id)
    if request.user == post.user:
        if request.method == 'POST':
            file = request.FILES.get('file')
            text = request.POST.get('text')
            if file:
                try:
                    post.text = text
                    post.image = file
                    post.video = file
                    post.save()

                    return redirect('index')
                except:
                    post.video = file
                    post.image = file
                    post.text = text
                    post.save()
                    return redirect('index')
            else:
                post.video = file
                post.image = file
                post.text = text
                post.save()
                return redirect('index')
    else:
        return redirect('index')

    context = {
        'post': post,
        'settings': settings
    }
    return render(request, 'posts/update_post.html', context)


def post_delete(request, id):
    settings = Settings.objects.latest('id')
    post = Post.objects.get(id=id)
    if request.user == post.user:
        if request.method == 'POST':
            post.delete()
            return redirect('index')

    else:
        return redirect('index')
    return render(request, 'posts/post_delete.html')


def comment_delete(request, id):
    settings = Settings.objects.latest('id')
    comment = Comment.objects.get(id=id)
    if request.user == comment.user:
        if request.method == 'POST':
            comment.delete()
            return redirect('index')
    else:
        return redirect('index')
    return render(request, 'posts/comment.html')


def search(request):
    posts = Post.objects.all()
    users = User.objects.all()
    search_key = request.GET.get('key')
    if search_key:
        posts = Post.objects.all().filter(Q(text__icontains=search_key))
        users = User.objects.all().filter(Q(username__icontains=search_key))
    context = {
        'users': users,
        'posts': posts,
    }
    return render(request, 'users/search.html', context)


def home(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:home')
    tasks = Task.objects.all()
    form = TaskForm()
    context = {
        'tasks': tasks,
        'form': form
    }
    return render(request, 'posts/todo_list.html', context)

def edit(request,id):
    task = Task.objects.get(id = id)
    if request.method == 'POST':
        form = UpdateForm(request.POST or None ,instance =task)
        if form.is_valid():
            form.save()
            return redirect('home:home')
    form = UpdateForm(request.POST or None,instance=task)
    context = {
        'form': form
    }
    return render(request, 'posts/edit.html', context)

def completed(request , id):
    task = Task.objects.get(id=id)
    if task.comleted != True:
        task.save()
        return redirect('home:home')

def delete(request,id):
    task = Task.objects.get(id = id)
    task.delete()
    return redirect('home:home')

def filter_priority(request,choice):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:home')
    tasks = Task.objects.filter(priority = choice)
    form = TaskForm()
    context = {
        'tasks': tasks,
        'form': form
    }
    return render(request, 'posts/todo_list.html', context)

def filter_status(request,choice):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:home')
    tasks = Task.objects.filter(status = choice)
    form = TaskForm()
    context = {
        'tasks': tasks,
        'form': form
    }
    return render(request, 'posts/todo_list.html', context)

templates/posts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Todo-S</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Add Bootstrap classes-->
        <link rel="stylesheet"
         href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
         crossorigin="anonymous">
         <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
         integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
         crossorigin="anonymous"></script>
         <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"
         integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf"
          crossorigin="anonymous"></script>

          <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
           integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
            crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

            <!-- Popper JS -->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

            <!-- Latest compiled JavaScript -->
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Add CSS here -->
            <style>
                body{
                    font-family: 'Open-Sans', sans-serif;
                    line-height: 1.6;
                }
                .add-todo-input {
                    outline: None;
                }
            </style>
</head>
<body>

{% block content %}

{% endblock %}

</body>
</html>

templates/posts/comment.html
{% extends 'homepage.html' %}
{% load static %}
{% block content %}
    <style>
        input , .bootstrap-select.btn-group button{
            background-color: #f3f4f6  !important;
            height: 44px  !important;
            box-shadow: none  !important; 
        }
    </style>


        
            <!-- Content-->
            <div>
                <div class="lg:p-12 max-w-xl lg:my-0 my-12 mx-auto p-6 space-y-">
                    <form method = 'POST' enctype="multipart/form-data" class="lg:p-10 p-6 space-y-3 relative bg-white shadow-xl rounded-md">
                        {% csrf_token %}
                        <h1 class="lg:text-2xl text-xl font-semibold mb-6">Are you sure with your ?<h1>

                        <div class="grid lg:grid-cols-1 gap-3">
                         
                        
                <div style='display:flex' >
                    <div style="margin-right: 20px;" class="flex space-x-2">
                        <button name="comment_delete" type="submit" class="bg-red-600 flex h-9 items-center justify-center rounded-md text-white px-5 font-medium">
                          удалить  </button>    
                    </div>
                      
                    <div class="flex space-x-2">
                        <a href="{% url 'index'%}" type="submit" class="bg-blue-600 flex h-9 items-center justify-center rounded-md text-white px-5 font-medium">
                          не удалять  </a>    
                    </div>
                </div>      
                    </form>



                </div>
            </div>
            
            <!-- Footer -->
    
        
    
        </div>

        
     
  {%endblock%}

templates/posts/edit.html
{% extends 'base.html' %}
{% block content %}
<div class="container m-5 p-2 rounded mx-auto bg-light shadow">

            <div class="row m-1 p-4">
                <div class="col">
                    <div class="p-1 h1 text-primary text-center display-inline-block">
                        <i class="fa fa-check bg-primary text-white p-2"></i>
                        <u>MY Todo-s</u>
                    </div>
                </div>
            </div>

            <!-- Create form -->
            <form method="POST">
                {% csrf_token %}

                <div class="row m-1 p-3">
                    <div class="col col-11 mx-auto">
                        <div class="row bg-white justify-content-center">
                            <div class="col">
                                <input type="text"  name="task_name" maxlength="200" required id="id_task_name"
                                 class="form-control form-control-lg border-0 add-todo-input bg-transparent " placeholder="Add New...">

                            </div>
                            <div class="col-auto m-0 px-2 d-flex align-items-center">
                                <input title="Set a due date" type="date" name="due_date" id="id_due_date">
                            </div>
                            <div class="col-auto px-0 mx-0 mr-2">
                                <input type="submit" class="btn btn-primary" value="Add" />
                            </div>
                        </div>
                    </div>
                </div>
            </form>

            <div class="p-2 mx-4 border-black-25 border-bottom" ></div>

            <!-- Add Task Table -->
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Task</th>
                        <th scope="col">
                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle" type="button"
                                 data-toggle="dropdown">
                                Priority
                                </button>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" href="{% url 'home:home' %}">ALL</a>
                                        <a class="dropdown-item" href="{% url 'home:priority' 'L' %}">Low</a>
                                        <a class="dropdown-item" href="{% url 'home:priority' 'M' %}">Medium</a>
                                        <a class="dropdown-item" href="{% url 'home:priority' 'H' %}">High</a>

                                    </li>

                                </ul>
                            </div>
                        </th>
                        <th scope="col">Due Date</th>
                        <th scope="col">
                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle" type="button"
                                 data-toggle="dropdown">
                                Status
                                </button>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" href="{% url 'home:home' %}">ALL</a>
                                        <a class="dropdown-item" href="{% url 'home:status' 'False' %}">Pending</a>
                                        <a class="dropdown-item" href="{% url 'home:status' 'True' %}">completed</a>

                                    </li>

                                </ul>
                            </div>
                        </th>

                    </tr>
                </thead>
                <tbody>
                {% for task in tasks %}
                    <tr>
                        <td scope="row">{{ forloop.counter }}</td>
                        <td scope="row">{{ task.task_name }}</td>
                        <td scope="row">{{ task.priority}}</td>
                        <td scope="row">{{ task.due_date}}</td>
                        <td scope="row">
                            {% if task.completed == True %}
                            Done
                            {% else %}
                            <a class="link" href="{% url 'home:completed' task.id %}">mark as complete</a>
                        {% endif %}
                        </td>
                        <td><a href="{% url 'home:edit' task.id %}"><i class="fa fa-edit text-primary"></i></a></td>
                        <td><a href="{% url 'home:delete' task.id%}"><i class="fa fa-trash text-danger"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>


{% endblock %}

templates/posts/post_delete.html
{% extends 'homepage.html' %}
{% load static %}
{% block content %}
    <style>
        input , .bootstrap-select.btn-group button{
            background-color: #f3f4f6  !important;
            height: 44px  !important;
            box-shadow: none  !important; 
        }
    </style>


        
            <!-- Content-->
            <div>
                <div class="lg:p-12 max-w-xl lg:my-0 my-12 mx-auto p-6 space-y-">
                    <form method = 'POST' enctype="multipart/form-data" class="lg:p-10 p-6 space-y-3 relative bg-white shadow-xl rounded-md">
                        {% csrf_token %}
                        <h1 class="lg:text-2xl text-xl font-semibold mb-6">Are you sure with your ?<h1>

                        <div class="grid lg:grid-cols-1 gap-3">
                         
                        
                <div style='display:flex' >
                    <div style="margin-right: 20px;" class="flex space-x-2">
                        <button name="post_delete" type="submit" class="bg-red-600 flex h-9 items-center justify-center rounded-md text-white px-5 font-medium">
                          удалить  </button>    
                    </div>
                      
                    <div class="flex space-x-2">
                        <a href="{% url 'index'%}" type="submit" class="bg-blue-600 flex h-9 items-center justify-center rounded-md text-white px-5 font-medium">
                          не удалять  </a>    
                    </div>
                </div>      
                    </form>



                </div>
            </div>
            
            <!-- Footer -->
    
        
    
        </div>

        
     
  {%endblock%}

templates/posts/todo_list.html
{% extends 'posts/base.html'%}

{% block content %}

<div class="container m-5 p-2 rounded mx-auto bg-light shadow">

    <div class="row m-1 p-4">
        <div class="col">
            <div class="p-1 h1 text-primary text-center display-inline-block">
                <i class="fa fa-check bg-primary text-white p-2"></i>
                <u>MY Todo-s</u>
            </div>
        </div>
    </div>

    <!-- Create form -->
    <form method="POST">
        {% csrf_token %}

        <div class="row m-1 p-3">
            <div class="col col-11 mx-auto">
                <div class="row bg-white justify-content-center">
                    <div class="col">
                        <input type="text" name="task_name" maxlength="200" required id="id_task_name"
                               class="form-control form-control-lg border-0 add-todo-input bg-transparent "
                               placeholder="Add New...">

                    </div>
                    <div class="col-auto m-0 px-2 d-flex align-items-center">
                        <input title="Set a due date" type="date" name="due_date" id="id_due_date">
                    </div>
                    <div class="col-auto px-0 mx-0 mr-2">
                        <input type="submit" class="btn btn-primary" value="Add"/>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <div class="p-2 mx-4 border-black-25 border-bottom"></div>

    <!-- Add Task Table -->
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Task</th>
            <th scope="col">
                <div class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" type="button"
                            data-toggle="dropdown">
                        Priority
                    </button>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" ">ALL</a>
                            <a class="dropdown-item" ">Low</a>
                            <a class="dropdown-item"  ">Medium</a>
                            <a class="dropdown-item" ">High</a>

                        </li>

                    </ul>
                </div>
            </th>
            <th scope="col">Due Date</th>
            <th scope="col">
                <div class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" type="button"
                            data-toggle="dropdown">
                        Status
                    </button>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" ">ALL</a>
                            <a class="dropdown-item" ">Pending</a>
                            <a class="dropdown-item" ">completed</a>

                        </li>

                    </ul>
                </div>
            </th>

        </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
        <tr>
            <td scope="row">{{ forloop.counter }}</td>
            <td scope="row">{{ task.task_name }}</td>
            <td scope="row">{{ task.priority}}</td>
            <td scope="row">{{ task.due_date}}</td>
            <td scope="row">
                {% if task.completed == True %}
                Done
                {% else %}
                {% comment %} <a class="link" href="{% url 'home:completed' task.id %}">mark as complete</a> {% endcomment %}
                {% endif %}
            </td>
            {% comment %} <td><a href="{% url 'home:edit' task.id %}"><i class="fa fa-edit text-primary"></i></a></td>
            <td><a href="{% url 'home:delete' task.id%}"><i class="fa fa-trash text-danger"></i></a></td> {% endcomment %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>


{% endblock content%}

templates/posts/update_post.html
{% extends 'homepage.html' %}
{% load static %}
{% block content %}
    <style>
        input , .bootstrap-select.btn-group button{
            background-color: #f3f4f6  !important;
            height: 44px  !important;
            box-shadow: none  !important; 
        }
    </style>


        
            <!-- Content-->
            <div>
                <div class="lg:p-12 max-w-xl lg:my-0 my-12 mx-auto p-6 space-y-">
                    <form method = 'POST' enctype="multipart/form-data" class="lg:p-10 p-6 space-y-3 relative bg-white shadow-xl rounded-md">
                        {% csrf_token %}
                        <h1 class="lg:text-2xl text-xl font-semibold mb-6"> update post </h1>

                        <div class="grid lg:grid-cols-1 gap-3">
                         
                        <div>
                            <label class="mb-0"> ведите текст </label>
                            <input name='text'   type="text" placeholder="ведите текст" class="bg-gray-100 h-12 mt-2 px-3 rounded-md w-full">
                        </div>
                        <div>
                            <label class="mb-0"> добавить фото для поста </label>
                            <input name='file' type="file"  class="bg-gray-100 h-12 mt-2 px-3 rounded-md w-full">
                        </div>
                    </div>
                    <div class="flex space-x-2">
                        <button name="create_post" type="submit" class="bg-blue-600 flex h-9 items-center justify-center rounded-md text-white px-5 font-medium">
                          update post </button>    
                    </div>
                    </form>


                </div>
            </div>
            
            <!-- Footer -->
    
        
    
        </div>

        
     
  {%endblock%}